# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 99ce6074bfd40ea8cb167339840516fa71ac3b9b2e1bce119d78d8c939b9a9b93bd0713dbe9cc050a27c66c6998bfa7553dbeefa267a4be3ae0a4f2f3c2ae3c1

test:
  secret_key_base: 8bb6705f7cbb468084e696256d8a0b04688d4f37523240793b2042d17b62e6538978b5f5569dc08614adfb3ed3474d6079b79aecfe2c1399fdb727fa9cc59cdf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
